version: 2

project_name: tpm-ca-certificates

builds:
  - id: tpmtb
    main: ./
    binary: tpmtb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.builtBy=goreleaser

archives:
  - id: tpmtb-archives
    ids:
      - tpmtb
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: "tpmtb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

docker_digest:
  name_template: "digests.txt"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# Signature in Sigstore bundle format
signs:
  - id: cosign-checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

dockers_v2:
  - images:
      - "ghcr.io/loicsikidi/tpm-ca-certificates/tpmtb"
    tags:
      - "v{{ .Version }}"
      - latest
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/loicsikidi/tpm-ca-certificates"

release:
  github:
    owner: loicsikidi
    name: tpm-ca-certificates
  draft: true
  prerelease: auto
  mode: append
  header: |
    ## {{ .ProjectName }} {{ .Tag }}

    ### What's Changed

    This release contains the `tpmtb` binary and OCI images built from commit [{{ .FullCommit }}](https://github.com/loicsikidi/{{ .ProjectName }}/tree/{{ .FullCommit }}).

    ### Artifacts

    - **`tpmtb_$VERSION_$OS_$ARCH.$EXTENSION`** - CLI binaries for various platforms (stored in archives)
    - **`tpmtb_$VERSION_$OS_$ARCH.$EXTENSION.sbom.json`** - SBOMs for the binaries in SPDX format
    - **`checksums.txt`** - SHA-256 checksums of all artifacts
    - **`checksums.txt.sigstore.json`** - Sigstore signature bundle for checksum verification

    ### OCI Images

    ```bash
    docker pull ghcr.io/loicsikidi/{{ .ProjectName }}/tpmtb:{{ .Tag }}
    docker pull ghcr.io/loicsikidi/{{ .ProjectName }}/tpmtb:latest
    ```

    ### Verification

    > [!IMPORTANT]
    > If you are not familiar with the concepts around software supply chain security,
    > (eg. build provenance attestation, keyless signature, etc.), please read the following resources first:
    > - [Cosign Signing Overview](https://docs.sigstore.dev/cosign/signing/overview/)
    > - [SLSA provenance attestation](https://slsa.dev/spec/v1.2/provenance)
    > - [GitHub attest-build-provenance action](https://github.com/actions/attest-build-provenance)

    #### 1. Artefacts with Cosign and GitHub CLI

    For complete security verification, follow this two-step process:

    **Step 1: Verify Integrity with Cosign**

    First, verify the **integrity** of the checksums file using Cosign:

    > [!TIP]
    > Make sure to use **`cosign >= v2.4.3`** to support the [Sigstore bundle format](https://docs.sigstore.dev/about/bundle/).

    ```bash
    # Verify the checksums signature
    cosign verify-blob \
      --bundle checksums.txt.sigstore.json \
      --certificate-identity-regexp 'https://github.com/loicsikidi/{{ .ProjectName }}/.github/workflows/release.yaml@refs/tags/{{ .Tag }}' \
      --certificate-oidc-issuer https://token.actions.githubusercontent.com \
      checksums.txt

    # Verify any artifact matches the checksum
    sha256sum -c checksums.txt
    ```

    **Step 2: Verify Provenance with GitHub CLI**

    Once the checksum integrity is established, verify the **provenance** using GitHub's attestation system:

    ```bash
    # Verify the archive
    gh attestation verify tpmtb_{{ .Version }}_linux_amd64.tar.gz --owner loicsikidi
    ```
    #### 2. OCI Provenance

    ```bash
    gh attestation verify oci://ghcr.io/loicsikidi/{{ .ProjectName }}/tpmtb:{{ .Tag }} --owner loicsikidi
    ```
  footer: |
    **Generated with GoReleaser 🚀**

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
