version: 2

project_name: tpm-ca-certificates

# Build du binaire tpmtb pour plusieurs plateformes
builds:
  - id: tpmtb
    main: ./
    binary: tpmtb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

# Archives des binaires tpmtb
archives:
  - id: tpmtb-archives
    ids:
      - tpmtb
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: "tpmtb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# Checksum de tous les artifacts
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

docker_digest:
  name_template: "digests.txt"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

# Signature Cosign v3 keyless
signs:
  - id: cosign-checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

dockers_v2:
  - images:
      - "ghcr.io/loicsikidi/tpm-ca-certificates/tpmtb"
    tags:
      - "v{{ .Version }}"
      - latest
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "https://github.com/loicsikidi/tpm-ca-certificates"

# Configuration de la release GitHub
release:
  github:
    owner: loicsikidi
    name: tpm-ca-certificates
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## {{ .ProjectName }} {{ .Tag }}

    ### What's Changed

    This release contains the `tpmtb` binary and OCI images built from commit [{{ .FullCommit }}](https://github.com/loicsikidi/{{ .ProjectName }}/tree/{{ .FullCommit }}).

    ### Artifacts

    - **`tpmtb_$VERSION_$OS_$ARCH.$EXTENSION`** - CLI binaries for various platforms (stored in archives)
    - **`tpmtb_$VERSION_$OS_$ARCH.$EXTENSION.sbom.json`** - SBOMs for the binaries in SPDX format
    - **`checksums.txt`** - SHA-256 checksums of all artifacts
    - **`checksums.txt.sigstore.json`** - Sigstore signature bundle for checksum verification

    ### OCI Images

    ```bash
    docker pull ghcr.io/loicsikidi/{{ .ProjectName }}:{{ .Tag }}
    docker pull ghcr.io/loicsikidi/{{ .ProjectName }}:latest
    ```

    ### Verification

    > [!IMPORTANT]
    > If you are not familiar with the concepts around software supply chain security,
    > (eg. build provenance attestation, keyless signature, etc.), please read the following resources first:
    > - [Cosign Signing Overview](https://docs.sigstore.dev/cosign/signing/overview/)
    > - [SLSA provenance attestation](https://slsa.dev/spec/v1.2/provenance)
    > - [GitHub attest-build-provenance action](https://github.com/actions/attest-build-provenance)

    #### Option 1: GitHub CLI

    > [!NOTE]
    > The following commands verify the **integrity** and **provenance** of an artifact using its associated cryptographic signed attestation
    > generated during the release process.

    ```bash
    # Verify the archive
    gh attestation verify tpmtb_{{ .Version }}_linux_amd64.tar.gz --owner loicsikidi
    # Verify the OCI image
    gh attestation verify oci://ghcr.io/loicsikidi/{{ .ProjectName }}:{{ .Tag }} --owner loicsikidi
    ```

    #### Option 2: Cosign

    > [!NOTE]
    > The following command verifies **ONLY the integrity** of the `checksums.txt` file
    > thanks to keyless signature generated during the release process. Once verified, you can
    > then manually check the checksum of any artifact.
    >
    > *Note: in addition, keyless signature allows you to know the identity bound to the ephemeral key (a GitHub workflow in our case).*

    > [!TIP]
    > Make sure to use **`cosign >= v2.4.3`** in order to support [sigstore bundle format](https://docs.sigstore.dev/about/bundle/).

    ```bash
    cosign verify-blob \
      --bundle checksums.txt.sigstore.json \
      --certificate-identity-regexp 'https://github.com/loicsikidi/{{ .ProjectName }}/.github/workflows/release.yaml@refs/tags/{{ .Tag }}' \
      --certificate-oidc-issuer https://token.actions.githubusercontent.com \
      checksums.txt

    # If the signature is OK, then you can verify any artifact located in the same directory
    sha256sum -c checksums.txt
    ```
  footer: |
    **Generated with GoReleaser 🚀**

# Changelog automatique
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
