version: 2

project_name: tpm-ca-certificates

# No build for this kind of release
builds:
  - skip: true

release:
  github:
    owner: loicsikidi
    name: tpm-ca-certificates
  draft: false
  prerelease: false
  mode: append
  extra_files:
    - glob: ./tpm-ca-certificates.pem
    - glob: ./checksums.txt
    - glob: ./checksums.txt.sigstore.json
  header: |
    ## TPM CA Certificates {{ .Tag }}

    ### What's Changed

    This release contains the TPM CA Certificates generated at commit [{{ .FullCommit }}](https://github.com/loicsikidi/{{ .ProjectName }}/tree/{{ .FullCommit }}).

    ### Artifacts

    - **`tpm-ca-certificates.pem`** - The TPM trust bundle
    - **`checksums.txt`** - SHA-256 checksum
    - **`checksums.txt.sigstore.json`** - Sigstore signature bundle for checksum verification

    ### Verification

    > [!IMPORTANT]
    > If you are not familiar with the concepts around software supply chain security,
    > (eg. build provenance attestation, keyless signature, etc.), please read the following resources first:
    > - [Cosign Signing Overview](https://docs.sigstore.dev/cosign/signing/overview/)
    > - [SLSA provenance attestation](https://slsa.dev/spec/v1.2/provenance)
    > - [GitHub attest-build-provenance action](https://github.com/actions/attest-build-provenance)

    #### Option 1: tpmtb CLI

    > [!NOTE]
    > The following commands verify the **integrity** and **provenance** of the `tpm-ca-certificates.pem` artifact
    >
    > `tpmtb` is able to verify Github attestation signatures and Cosign keyless signatures natively (no need to install Cosign or gh).

    ```bash
    tpmtb bundle verify tpm-ca-certificates.pem
    ```

    #### Option 2: Cosign and GitHub CLI

    The following process does the same thing as option 1:

    **Step 1: Verify Integrity with Cosign**

    First, verify the **integrity** of the checksums file using Cosign:

    > [!IMPORTANT]
    > Make sure to use **`cosign >= v2.4.3`** to support the [Sigstore bundle format](https://docs.sigstore.dev/about/bundle/).

    ```bash
    # Verify the checksums signature
    cosign verify-blob \
      --bundle checksums.txt.sigstore.json \
      --certificate-identity-regexp 'https://github.com/loicsikidi/{{ .ProjectName }}/.github/workflows/release-bundle.yaml@refs/tags/{{ .Tag }}' \
      --certificate-oidc-issuer https://token.actions.githubusercontent.com \
      checksums.txt

    # Verify the bundle matches the checksum
    sha256sum -c checksums.txt
    ```

    **Step 2: Verify Provenance with GitHub CLI**

    Once the checksum integrity is established, verify the **provenance** using GitHub's attestation system:

    ```bash
    gh attestation verify tpm-ca-certificates.pem --owner loicsikidi
    ```

    #### Option 3: Reproducibility

    > [!WARNING]
    > This method only verifies the **integrity** of `tpm-ca-certificates.pem` file.
    > To be fully secure it MUST be used in addition with `gh attestation verify` to validate provenance.

    ```bash
    git clone https://github.com/loicsikidi/{{ .ProjectName }}
    cd {{ .ProjectName }}
    git checkout {{ .Tag }}
    go run ./ generate --workers 10 --output tpm-ca-certificates.pem
    sha256sum tpm-ca-certificates.pem  # Compare with checksums.txt
    ```
  footer: |
    **Generated with GoReleaser 🚀**

changelog:
  use: github
  sort: asc
  filters:
    # Include only commits starting with "rot:" (prefix for "root of trust" changes)
    include:
      - '^rot:' 
