---
version: "alpha"
vendors:
    - id: "IFX"
      name: "Infineon"
      certificates:
        - name: "Infineon OPTIGA(TM) ECC Root CA"
          url: "https://www.infineon.com/assets/row/public/documents/30/67/infineon-optigatm-trust-ecc-root-ca-certificates-en.cer"
          validation:
            fingerprint:
                sha256: "CF:EB:02:FE:CD:55:AD:7A:73:C6:E1:D1:19:85:D4:C4:7D:EE:24:8A:B6:3D:CB:66:09:1A:24:89:66:04:43:C3"
        - name: "Infineon OPTIGA(TM) ECC Root CA 2"
          url: "https://pki.infineon.com/OptigaEccRootCA2/OptigaEccRootCA2.crt"
          validation:
            fingerprint:
                sha256: "EE:0C:82:75:55:C4:E9:01:20:37:DF:42:57:BB:8A:AA:26:08:4A:17:B1:3E:DE:41:CD:78:95:C8:D6:C1:11:90"
        - name: "Infineon OPTIGA(TM) ECC Root CA 3"
          url: "https://pki.infineon.com/OptigaEccRootCA3/OptigaEccRootCA3.crt"
          validation:
            fingerprint:
                sha256: "5A:84:CC:34:76:22:1C:CE:5B:E8:1A:F8:D7:55:D1:75:FE:A0:3D:20:8B:34:12:A2:31:71:0C:56:77:45:42:FD"
        - name: "Infineon OPTIGA(TM) RSA Root CA"
          url: "https://pki.infineon.com/OptigaRsaRootCA/OptigaRsaRootCA.crt"
          validation:
            fingerprint:
                sha256: "89:9E:35:47:4C:98:07:EB:4C:7F:2F:7A:12:DA:00:28:FB:25:0C:D0:21:54:D0:00:9F:CA:7D:9C:66:57:4F:3B"
        - name: "Infineon OPTIGA(TM) RSA Root CA 2"
          url: "https://pki.infineon.com/OptigaRsaRootCA2/OptigaRsaRootCA2.crt"
          validation:
            fingerprint:
                sha256: "B4:13:C7:15:80:AF:3E:C5:EF:E8:3F:AD:31:DB:2D:4A:F4:61:23:55:E3:B0:1E:50:90:3B:10:76:3D:73:88:94"
        - name: "Infineon OPTIGA(TM) RSA Root CA 3"
          url: "https://pki.infineon.com/OptigaRsaRootCA3/OptigaRsaRootCA3.crt"
          validation:
            fingerprint:
                sha256: "97:6B:05:79:C0:16:74:1B:00:03:BF:80:55:E9:20:AB:08:F7:2A:BC:81:95:47:B3:48:0B:0C:14:1E:95:6B:70"
    - id: "INTC"
      name: "Intel"
      certificates:
        - name: "OnDie CA RootCA"
          url: "https://tsci.intel.com/content/OnDieCA/certs/OnDie_CA_RootCA_Certificate.cer"
          validation:
            fingerprint:
                sha256: "BE:B4:0B:B7:50:7B:33:96:72:26:AA:80:E0:84:74:9F:BB:65:93:89:3C:64:2E:81:8D:68:2E:9A:8D:07:FC:24"
    - id: "MSFT"
      name: "Microsoft"
      certificates:
        - name: "Microsoft Pluton Root CA 2021"
          url: "https://www.microsoft.com/pkiops/certs/Microsoft%20Pluton%20Root%20CA%202021.crt"
          validation:
            fingerprint:
                sha256: "32:AB:5F:E7:CB:43:96:65:9F:CB:62:1C:A1:4C:6F:B8:FC:24:20:F6:40:50:63:7D:77:E4:5A:86:C5:D3:91:6E"
        - name: "Microsoft TPM Root Certificate Authority 2014"
          url: "https://www.microsoft.com/pkiops/certs/Microsoft%20TPM%20Root%20Certificate%20Authority%202014.crt"
          validation:
            fingerprint:
                sha256: "87:0C:7A:35:CE:AB:3D:59:97:9F:2C:6A:52:40:42:D4:04:CB:71:51:80:04:35:09:25:FB:2C:ED:79:A9:99:DA"
    - id: "NTC"
      name: "Nuvoton Technology"
      certificates:
        - name: "NPCTxxx ECC521 RootCA"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/NPCTxxxECC521RootCA.cer"
          validation:
            fingerprint:
                sha1: "7C:7B:3C:8A:46:5E:67:D2:8F:4D:B0:F3:5C:E1:20:C4:BB:4A:AC:CC"
        - name: "Nuvoton TPM Root CA 1110"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton%20TPM%20Root%20CA%201110.cer"
          validation:
            fingerprint:
                sha1: "65:5E:44:5E:96:54:5C:F3:E4:84:82:94:9B:35:A7:CE:B3:46:58:CC"
        - name: "Nuvoton TPM Root CA 1111"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton%20TPM%20Root%20CA%201111.cer"
          validation:
            fingerprint:
                sha1: "48:65:2A:31:B9:D2:66:08:4E:2A:E9:82:D8:B6:73:26:D6:6C:73:72"
        - name: "Nuvoton TPM Root CA 2111"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton%20TPM%20Root%20CA%202111.cer"
          validation:
            fingerprint:
                sha1: "A3:43:0D:4E:2F:07:55:61:96:5A:E6:ED:32:C9:1A:3D:73:22:C4:2B"
        - name: "Nuvoton TPM Root CA 2112"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/Nuvoton%20TPM%20Root%20CA%202112.cer"
          validation:
            fingerprint:
                sha1: "58:9A:6B:D9:EE:96:3B:EC:E2:06:58:D1:4A:24:0F:7B:4B:72:40:33"
        - name: "NuvotonTPMRootCA1210"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/NuvotonTPMRootCA1210.cer"
          validation:
            fingerprint:
                sha1: "86:A9:9E:10:F6:B1:1E:41:BD:19:D8:EF:79:DB:C9:5A:F4:D3:C3:ED"
        - name: "NuvotonTPMRootCA2210"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/NuvotonTPMRootCA2210.cer"
          validation:
            fingerprint:
                sha1: "4A:D6:DD:BD:52:52:2C:52:1C:BF:92:99:C4:46:26:3F:34:81:A6:7A"
        - name: "NuvotonTPMRootCA2211"
          url: "https://www.nuvoton.com/security/NTC-TPM-EK-Cert/NuvotonTPMRootCA2211.cer"
          validation:
            fingerprint:
                sha1: "5E:74:87:90:69:4F:6A:7F:6E:AB:AF:70:15:26:86:3C:DD:FE:6D:AC"
    - id: "STM"
      name: "STMicroelectronics"
      certificates:
        - name: "GlobalSign Trusted Platform Module ECC Root CA"
          url: "https://secure.globalsign.com/cacert/tpmeccroot.crt"
          validation:
            fingerprint:
                sha256: "5A:8C:7B:5E:B8:88:CF:CE:93:22:06:8E:80:E8:2B:28:B5:54:FF:EB:7F:DC:96:38:DC:B3:76:30:77:40:1D:26"
        - name: "GlobalSign Trusted Platform Module Root CA"
          url: "https://secure.globalsign.com/cacert/gstpmroot.crt"
          validation:
            fingerprint:
                sha256: "F2:7B:F0:2C:6E:00:C7:3D:91:5E:EB:6A:6A:2F:5F:BF:0C:31:AE:03:93:14:9E:6B:5C:31:E4:1B:11:38:41:C3"
        - name: "STM TPM ECC Root CA 01"
          url: "https://secure.globalsign.com/cacert/stmtpmeccroot01.crt"
          validation:
            fingerprint:
                sha256: "C5:41:D7:E5:B9:E3:F9:35:62:1A:CB:D4:03:89:62:25:EC:64:10:36:C9:AE:3B:5F:7A:C7:93:A6:06:FF:9B:79"
        - name: "STM TPM EK Root CA"
          url: "https://secure.globalsign.com/cacert/stmtpmekroot.crt"
          validation:
            fingerprint:
                sha256: "F8:E3:7A:86:B6:89:A2:0A:6C:C0:C4:0C:C3:F8:1F:B1:30:FA:9F:44:CE:7F:FA:60:D6:25:90:AA:F8:72:73:A9"
        - name: "STSAFE ECC Root CA 02"
          url: "https://sw-center.st.com/STSAFE/STSAFEEccRootCA02.crt"
          validation:
            fingerprint:
                sha256: "FD:1E:7B:68:AC:CD:82:56:36:B2:7B:31:77:C6:74:02:D4:63:A7:F0:4C:97:B6:C4:7A:B7:05:FC:DC:1A:04:F6"
        - name: "STSAFE RSA Root CA 02"
          url: "https://sw-center.st.com/STSAFE/STSAFERsaRootCA02.crt"
          validation:
            fingerprint:
                sha256: "C8:F1:79:94:33:56:E1:3D:9D:84:B1:00:20:1C:EF:AB:BF:40:88:80:24:1E:53:29:E6:0D:95:0C:E1:DE:A6:23"
