extensions = ["md"]
timeout = 30 # in seconds
header = { "accept" = "text/html" }
accept = [
    "200..=202",
    "403", # it's ok if the scrap is forbidden
    "429",
    "502", # it's ok if the backend is down during the scan
    "503", # it's ok if the backend is down during the scan
]
exclude = [
    '^https://pki\.infineon\.com',
    '^https://www\.st\.com',
    '^https://software\.intel\.com',
    '^https://(.*\.)?github(usercontent)?\.(com|io)',
    '^https://pki\.nationstech\.com/NSTPMEccEkCA%7B001-005%7D/',
    '^https://pki\.nationstech\.com/NSTPMRsaEkCA%7B001-005%7D/',
    'http://localhost:16686',
]
