---
version: "alpha"
vendors:
    - id: "IFX"
      name: "Infineon"
      certificates:
        - name: "Infineon OPTIGA(TM) ECC Root CA 3"
          url: "https://pki.infineon.com/OptigaEccRootCA3/OptigaEccRootCA3.crt"
          validation:
            fingerprint:
                sha256: "5A:84:CC:34:76:22:1C:CE:5B:E8:1A:F8:D7:55:D1:75:FE:A0:3D:20:8B:34:12:A2:31:71:0C:56:77:45:42:FD"
        - name: "Infineon OPTIGA(TM) RSA Root CA 3"
          url: "https://pki.infineon.com/OptigaRsaRootCA3/OptigaRsaRootCA3.crt"
          validation:
            fingerprint:
                sha256: "97:6B:05:79:C0:16:74:1B:00:03:BF:80:55:E9:20:AB:08:F7:2A:BC:81:95:47:B3:48:0B:0C:14:1E:95:6B:70"
